// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export class DisplayState {
    /**
     * Creates a new DisplayState instance.
     * @param {Partial<DisplayState>} [$$source = {}] - The source object to create the DisplayState.
     */
    constructor($$source = {}) {
        if (!("uuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uuid"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("main" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["main"] = false;
        }
        if (!("bindingID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bindingID"] = "";
        }
        if (!("profileID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profileID"] = "";
        }
        if (!("spaceKind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["spaceKind"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplayState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DisplayState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisplayState(/** @type {Partial<DisplayState>} */($$parsedSource));
    }
}

export class Item {
    /**
     * Creates a new Item instance.
     * @param {Partial<Item>} [$$source = {}] - The source object to create the Item.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Item}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item(/** @type {Partial<Item>} */($$parsedSource));
    }
}

export class Presentation {
    /**
     * Creates a new Presentation instance.
     * @param {Partial<Presentation>} [$$source = {}] - The source object to create the Presentation.
     */
    constructor($$source = {}) {
        if (!("edge" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["edge"] = "";
        }
        if (!("layout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["layout"] = "";
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {config$0.LauncherAppearance}
             */
            this["appearance"] = (new config$0.LauncherAppearance());
        }
        if (!("epoch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["epoch"] = 0;
        }
        if (!("displayUUID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayUUID"] = "";
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session"] = 0;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visible"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("profileID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profileID"] = "";
        }
        if (!("bounds" in $$source)) {
            /**
             * @member
             * @type {domain$0.Bounds}
             */
            this["bounds"] = (new domain$0.Bounds());
        }
        if (!("iconPx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iconPx"] = 0;
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {Item[]}
             */
            this["items"] = [];
        }
        if (!("widgets" in $$source)) {
            /**
             * @member
             * @type {Widget[]}
             */
            this["widgets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Presentation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Presentation}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        const $$createField12_0 = $$createType3;
        const $$createField13_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField2_0($$parsedSource["appearance"]);
        }
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField10_0($$parsedSource["bounds"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField12_0($$parsedSource["items"]);
        }
        if ("widgets" in $$parsedSource) {
            $$parsedSource["widgets"] = $$createField13_0($$parsedSource["widgets"]);
        }
        return new Presentation(/** @type {Partial<Presentation>} */($$parsedSource));
    }
}

export class Widget {
    /**
     * Creates a new Widget instance.
     * @param {Partial<Widget>} [$$source = {}] - The source object to create the Widget.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("packageID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packageID"] = "";
        }
        if (!("digest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["digest"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {WidgetNode}
             */
            this["root"] = (new WidgetNode());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Widget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Widget}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("root" in $$parsedSource) {
            $$parsedSource["root"] = $$createField4_0($$parsedSource["root"]);
        }
        return new Widget(/** @type {Partial<Widget>} */($$parsedSource));
    }
}

export class WidgetNode {
    /**
     * Creates a new WidgetNode instance.
     * @param {Partial<WidgetNode>} [$$source = {}] - The source object to create the WidgetNode.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {WidgetNode[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WidgetNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WidgetNode}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField2_0($$parsedSource["children"]);
        }
        return new WidgetNode(/** @type {Partial<WidgetNode>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = config$0.LauncherAppearance.createFrom;
const $$createType1 = domain$0.Bounds.createFrom;
const $$createType2 = Item.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Widget.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = WidgetNode.createFrom;
const $$createType7 = $Create.Array($$createType6);
