// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";

export class FolderState {
    /**
     * Creates a new FolderState instance.
     * @param {Partial<FolderState>} [$$source = {}] - The source object to create the FolderState.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("folderIdentity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderIdentity"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {platform$0.FolderEntry[]}
             */
            this["entries"] = [];
        }
        if (!("sort" in $$source)) {
            /**
             * @member
             * @type {platform$0.FolderSort}
             */
            this["sort"] = (new platform$0.FolderSort());
        }
        if (!("partial" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["partial"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderState}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField4_0($$parsedSource["entries"]);
        }
        if ("sort" in $$parsedSource) {
            $$parsedSource["sort"] = $$createField5_0($$parsedSource["sort"]);
        }
        return new FolderState(/** @type {Partial<FolderState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = platform$0.FolderEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = platform$0.FolderSort.createFrom;
