// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Failure uses WindowID zero for a snapshot-wide incomplete-enumeration error.
 */
export class Failure {
    /**
     * Creates a new Failure instance.
     * @param {Partial<Failure>} [$$source = {}] - The source object to create the Failure.
     */
    constructor($$source = {}) {
        if (!("windowId" in $$source)) {
            /**
             * @member
             * @type {domain$0.WindowID}
             */
            this["windowId"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Failure instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Failure}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Failure(/** @type {Partial<Failure>} */($$parsedSource));
    }
}

export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("succeeded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["succeeded"] = 0;
        }
        if (!("failures" in $$source)) {
            /**
             * @member
             * @type {Failure[]}
             */
            this["failures"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failures" in $$parsedSource) {
            $$parsedSource["failures"] = $$createField1_0($$parsedSource["failures"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Failure.createFrom;
const $$createType1 = $Create.Array($$createType0);
