// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Appearance controls the look of the overlay.
 */
export class Appearance {
    /**
     * Creates a new Appearance instance.
     * @param {Partial<Appearance>} [$$source = {}] - The source object to create the Appearance.
     */
    constructor($$source = {}) {
        if (!("style" in $$source)) {
            /**
             * @member
             * @type {VisualStyle}
             */
            this["style"] = VisualStyle.$zero;
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {Theme}
             */
            this["theme"] = Theme.$zero;
        }
        if (!("sizePreset" in $$source)) {
            /**
             * SizePreset is the coarse overlay size; the preferences UI derives the
             * pixel fields below from it (they remain authoritative for rendering).
             * @member
             * @type {SizePreset}
             */
            this["sizePreset"] = SizePreset.$zero;
        }
        if (!("maxRows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRows"] = 0;
        }
        if (!("maxColumns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxColumns"] = 0;
        }
        if (!("thumbnailMaxPx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thumbnailMaxPx"] = 0;
        }
        if (!("iconSizePx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iconSizePx"] = 0;
        }
        if (!("titleMaxWidthPx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["titleMaxWidthPx"] = 0;
        }
        if (!("fontSizePx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fontSizePx"] = 0;
        }
        if (!("accentColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accentColor"] = "";
        }
        if (!("backgroundOpacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backgroundOpacity"] = 0;
        }
        if (!("blur" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["blur"] = false;
        }
        if (!("cornerRadiusPx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cornerRadiusPx"] = 0;
        }
        if (!("showAppBadge" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showAppBadge"] = false;
        }
        if (!("showTitle" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showTitle"] = false;
        }
        if (!("showWindowControls" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showWindowControls"] = false;
        }
        if (!("autoSize" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoSize"] = false;
        }
        if (!("apparitionDelayMs" in $$source)) {
            /**
             * ApparitionDelayMs postpones showing the overlay so quick app switches
             * don't flash it (AltTab's "apparition delay").
             * @member
             * @type {number}
             */
            this["apparitionDelayMs"] = 0;
        }
        if (!("fadeOutAnimation" in $$source)) {
            /**
             * FadeOutAnimation animates the overlay's dismissal.
             * @member
             * @type {boolean}
             */
            this["fadeOutAnimation"] = false;
        }
        if (!("showStatusIcons" in $$source)) {
            /**
             * ShowStatusIcons shows the minimized/hidden/fullscreen markers.
             * @member
             * @type {boolean}
             */
            this["showStatusIcons"] = false;
        }
        if (!("showSpaceNumbers" in $$source)) {
            /**
             * ShowSpaceNumbers shows Space number badges on windows of other Spaces.
             * @member
             * @type {boolean}
             */
            this["showSpaceNumbers"] = false;
        }
        if (!("titleTruncation" in $$source)) {
            /**
             * TitleTruncation is where long titles are elided (end/middle/start).
             * @member
             * @type {TruncationMode}
             */
            this["titleTruncation"] = TruncationMode.$zero;
        }
        if (!("previewSelected" in $$source)) {
            /**
             * PreviewSelected shows a large preview of the selected window.
             * @member
             * @type {boolean}
             */
            this["previewSelected"] = false;
        }
        if (!("previewFade" in $$source)) {
            /**
             * PreviewFade fades the selected-window preview in when it changes.
             * @member
             * @type {boolean}
             */
            this["previewFade"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Appearance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Appearance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Appearance(/** @type {Partial<Appearance>} */($$parsedSource));
    }
}

/**
 * Placement is where the overlay appears.
 * @readonly
 * @enum {string}
 */
export const Placement = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlaceActiveScreen: "activeScreen",
    PlaceCursorScreen: "cursorScreen",
    PlaceFocusedWindowScreen: "focusedWindowScreen",
};

/**
 * SizePreset is the coarse switcher size (AltTab's Small/Medium/Large): it
 * drives the thumbnail/icon pixel sizes from one user-facing control.
 * @readonly
 * @enum {string}
 */
export const SizePreset = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SizeSmall: "small",
    SizeMedium: "medium",
    SizeLarge: "large",
};

/**
 * Theme selects the color scheme.
 * @readonly
 * @enum {string}
 */
export const Theme = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ThemeSystem: "system",
    ThemeLight: "light",
    ThemeDark: "dark",
};

/**
 * TruncationMode is where long window titles get elided.
 * @readonly
 * @enum {string}
 */
export const TruncationMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TruncateEnd: "end",
    TruncateMiddle: "middle",
    TruncateStart: "start",
};

/**
 * VisualStyle is how the switcher renders each entry.
 * @readonly
 * @enum {string}
 */
export const VisualStyle = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StyleThumbnails: "thumbnails",
    StyleAppIcons: "appIcons",
    StyleTitles: "titles",
};
