// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    DockLockDisplay,
    DockMonitorLockState,
    DockPlacementResult,
    FolderEntry,
    FolderSort,
    WindowPresence
} from "./models.js";
