// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    DiagnosticExportResult,
    DockLockDisplay,
    DockMonitorLockState,
    DockPlacementResult,
    FolderEntry,
    FolderSort,
    MediaCapabilities,
    MediaPermission,
    MediaProcess,
    MediaProvider,
    MediaSample,
    MediaScope,
    MediaTrack,
    WindowPresence
} from "./models.js";
