// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WindowPresence separates a positively empty inventory from unavailable AX
 * metadata. Unknown apps can still be activated, but do not acquire invented
 * window targets or satisfy the "hide when no windows" rule.
 * @readonly
 * @enum {string}
 */
export const WindowPresence = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    WindowsPresent: "present",
    WindowsNone: "none",
    WindowsUnknown: "unknown",
};
