// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Entry is one window as presented to the view (JSON-serializable).
 */
export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("windowId" in $$source)) {
            /**
             * @member
             * @type {domain$0.WindowID}
             */
            this["windowId"] = 0;
        }
        if (!("appId" in $$source)) {
            /**
             * @member
             * @type {domain$0.AppID}
             */
            this["appId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("bundleId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bundleId"] = "";
        }
        if (!("spaceId" in $$source)) {
            /**
             * @member
             * @type {domain$0.SpaceID}
             */
            this["spaceId"] = 0;
        }
        if (!("minimized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["minimized"] = false;
        }
        if (!("hidden" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hidden"] = false;
        }
        if (!("fullscreen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fullscreen"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Icon is a base64 PNG data URL of the owning app's icon. The controller
             * leaves it empty; the view layer fills it (platform-specific).
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}

/**
 * State is the full switcher snapshot handed to the view.
 */
export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["open"] = false;
        }
        if (!("style" in $$source)) {
            /**
             * @member
             * @type {config$0.VisualStyle}
             */
            this["style"] = config$0.VisualStyle.$zero;
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {config$0.Appearance}
             */
            this["appearance"] = (new config$0.Appearance());
        }
        if (!("placement" in $$source)) {
            /**
             * @member
             * @type {config$0.Placement}
             */
            this["placement"] = config$0.Placement.$zero;
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {Entry[]}
             */
            this["entries"] = [];
        }
        if (!("selected" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["selected"] = 0;
        }
        if (!("search" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["search"] = "";
        }
        if (!("shortcutId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["shortcutId"] = 0;
        }
        if (!("vimKeys" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vimKeys"] = false;
        }
        if (!("arrowKeys" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["arrowKeys"] = false;
        }
        if (!("mouseHover" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mouseHover"] = false;
        }
        if (!("activeSpaceId" in $$source)) {
            /**
             * @member
             * @type {domain$0.SpaceID}
             */
            this["activeSpaceId"] = 0;
        }
        if (!("placementScreenId" in $$source)) {
            /**
             * PlacementScreenID is the display the overlay window is sized to appear on.
             * @member
             * @type {domain$0.ScreenID}
             */
            this["placementScreenId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField2_0($$parsedSource["appearance"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField4_0($$parsedSource["entries"]);
        }
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = config$0.Appearance.createFrom;
const $$createType1 = Entry.createFrom;
const $$createType2 = $Create.Array($$createType1);
