// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActionOption {
    /**
     * Creates a new ActionOption instance.
     * @param {Partial<ActionOption>} [$$source = {}] - The source object to create the ActionOption.
     */
    constructor($$source = {}) {
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionOption(/** @type {Partial<ActionOption>} */($$parsedSource));
    }
}

export class ActionOptions {
    /**
     * Creates a new ActionOptions instance.
     * @param {Partial<ActionOptions>} [$$source = {}] - The source object to create the ActionOptions.
     */
    constructor($$source = {}) {
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {ActionOption[]}
             */
            this["options"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {NumberRange | null | undefined}
             */
            this["range"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionOptions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField0_0($$parsedSource["options"]);
        }
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField1_0($$parsedSource["range"]);
        }
        return new ActionOptions(/** @type {Partial<ActionOptions>} */($$parsedSource));
    }
}

export class InstanceState {
    /**
     * Creates a new InstanceState instance.
     * @param {Partial<InstanceState>} [$$source = {}] - The source object to create the InstanceState.
     */
    constructor($$source = {}) {
        if (!("lease" in $$source)) {
            /**
             * @member
             * @type {Lease}
             */
            this["lease"] = (new Lease());
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {RenderNode}
             */
            this["root"] = (new RenderNode());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstanceState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstanceState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lease" in $$parsedSource) {
            $$parsedSource["lease"] = $$createField0_0($$parsedSource["lease"]);
        }
        if ("root" in $$parsedSource) {
            $$parsedSource["root"] = $$createField3_0($$parsedSource["root"]);
        }
        return new InstanceState(/** @type {Partial<InstanceState>} */($$parsedSource));
    }
}

export class Lease {
    /**
     * Creates a new Lease instance.
     * @param {Partial<Lease>} [$$source = {}] - The source object to create the Lease.
     */
    constructor($$source = {}) {
        if (!("controllerEpoch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["controllerEpoch"] = 0;
        }
        if (!("displayUUID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayUUID"] = "";
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session"] = 0;
        }
        if (!("profileID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profileID"] = "";
        }
        if (!("instanceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instanceID"] = "";
        }
        if (!("digest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["digest"] = "";
        }
        if (!("admissionEpoch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["admissionEpoch"] = 0;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Lease instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Lease}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Lease(/** @type {Partial<Lease>} */($$parsedSource));
    }
}

/**
 * @typedef {{ [_ in string]?: string }} Localized
 */

export class NumberRange {
    /**
     * Creates a new NumberRange instance.
     * @param {Partial<NumberRange>} [$$source = {}] - The source object to create the NumberRange.
     */
    constructor($$source = {}) {
        if (!("min" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["min"] = 0;
        }
        if (!("max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max"] = 0;
        }
        if (!("step" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["step"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NumberRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NumberRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NumberRange(/** @type {Partial<NumberRange>} */($$parsedSource));
    }
}

export class RenderNode {
    /**
     * Creates a new RenderNode instance.
     * @param {Partial<RenderNode>} [$$source = {}] - The source object to create the RenderNode.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["progress"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["history"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["assetToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["actionToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RenderNode[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RenderNode}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType6;
        const $$createField8_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField5_0($$parsedSource["history"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField8_0($$parsedSource["children"]);
        }
        return new RenderNode(/** @type {Partial<RenderNode>} */($$parsedSource));
    }
}

export class Setting {
    /**
     * Creates a new Setting instance.
     * @param {Partial<Setting>} [$$source = {}] - The source object to create the Setting.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {Localized}
             */
            this["name"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["defaultText"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["defaultNumber"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["defaultBool"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["min"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["max"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Setting}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType8;
        const $$createField6_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField2_0($$parsedSource["name"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new Setting(/** @type {Partial<Setting>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ActionOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = NumberRange.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = Lease.createFrom;
const $$createType5 = RenderNode.createFrom;
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Array($$createType5);
var $$createType8 = /** @type {(...args: any[]) => any} */(function $$initCreateType8(...args) {
    if ($$createType8 === $$initCreateType8) {
        $$createType8 = $$createType9;
    }
    return $$createType8(...args);
});
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $Create.Array($Create.Any);
