// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails-bound service. It owns the platform backend and the switcher
 * controller, implements switcher.View by emitting Wails events, and exposes
 * the controller's actions plus settings access to the frontend. It holds no
 * business logic of its own.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "./internal/actions/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcher$0 from "./internal/launcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "./internal/platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as switcher$0 from "./internal/switcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as widgets$0 from "./internal/widgets/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ActionFailed(message) {
    return $Call.ByID(2458319746, message);
}

/**
 * @param {number} epoch
 * @param {string} displayUUID
 * @param {number} session
 * @param {number} revision
 * @param {string} itemID
 * @returns {$CancellablePromise<void>}
 */
export function ActivateLauncherItem(epoch, displayUUID, session, revision, itemID) {
    return $Call.ByID(529143415, epoch, displayUUID, session, revision, itemID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Advance() {
    return $Call.ByID(3974603045);
}

/**
 * @param {number} session
 * @param {number} gesture
 * @param {number} windowID
 * @param {number} appID
 * @param {number} pointerX
 * @param {number} pointerY
 * @param {number} grabX
 * @param {number} grabY
 * @returns {$CancellablePromise<void>}
 */
export function BeginDockPreviewDrag(session, gesture, windowID, appID, pointerX, pointerY, grabX, grabY) {
    return $Call.ByID(3337788529, session, gesture, windowID, appID, pointerX, pointerY, grabX, grabY);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(2191755235);
}

/**
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function CancelDockFolderAccess(session, revision) {
    return $Call.ByID(3062959714, session, revision);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelDockPlacement() {
    return $Call.ByID(2631637315);
}

/**
 * @param {number} session
 * @param {number} gesture
 * @returns {$CancellablePromise<void>}
 */
export function CancelDockPreviewDrag(session, gesture) {
    return $Call.ByID(418174098, session, gesture);
}

/**
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function CancelMediaLyricsImport(session, revision) {
    return $Call.ByID(3785335492, session, revision);
}

/**
 * CancelShortcutCapture disarms a pending shortcut capture (the recorder
 * input lost focus).
 * @returns {$CancellablePromise<void>}
 */
export function CancelShortcutCapture() {
    return $Call.ByID(1824023725);
}

/**
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function CancelWidgetPackageReview(token) {
    return $Call.ByID(1933127773, token);
}

/**
 * CaptureShortcut arms native chord recording for the preferences UI and
 * blocks until the next chord pressed anywhere — including Command+Tab and
 * the switcher's own chord, which never reach the webview. Returns "" when
 * cancelled (Escape), timed out, or unsupported (stub platforms).
 * @returns {$CancellablePromise<string>}
 */
export function CaptureShortcut() {
    return $Call.ByID(1771599287);
}

/**
 * CheckForUpdates runs a release check now and reveals the Updates section of
 * the General tab, where the check's outcome appears (the install banner is
 * app-level chrome, shown on every tab). The manual check never auto-installs,
 * even under the "auto" policy.
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2675659504);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearDiagnostics() {
    return $Call.ByID(2969743170);
}

/**
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function CloseAutomationPreview(session, revision) {
    return $Call.ByID(43965240, session, revision);
}

/**
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function CloseMediaPanel(session, revision) {
    return $Call.ByID(231734221, session, revision);
}

/**
 * ClosePreferences hides the preferences window and returns the app to the
 * accessory policy (no Dock icon).
 * @returns {$CancellablePromise<void>}
 */
export function ClosePreferences() {
    return $Call.ByID(3493222023);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseSelected() {
    return $Call.ByID(2868361114);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Confirm() {
    return $Call.ByID(3228319335);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmApp(id) {
    return $Call.ByID(1759019970, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmWindow(id) {
    return $Call.ByID(3813603255, id);
}

/**
 * @param {string} provider
 * @returns {$CancellablePromise<platform$0.MediaPermission>}
 */
export function ConnectMediaProvider(provider) {
    return $Call.ByID(2624774846, provider).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DismissCrashReport discards the pending crash log.
 * @returns {$CancellablePromise<void>}
 */
export function DismissCrashReport() {
    return $Call.ByID(2108673700);
}

/**
 * @param {number} session
 * @param {number} windowID
 * @param {number} appID
 * @returns {$CancellablePromise<actions$0.Result>}
 */
export function FocusDockWindow(session, windowID, appID) {
    return $Call.ByID(1587026944, session, windowID, appID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function FullscreenSelected() {
    return $Call.ByID(529416953);
}

/**
 * @param {number} session
 * @returns {$CancellablePromise<$models.AutomationPreviewViewState | null>}
 */
export function GetAutomationPreviewState(session) {
    return $Call.ByID(473218209, session).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCrashReport returns the previous run's crash log, or "" when there is
 * none (or the policy is "never").
 * @returns {$CancellablePromise<string>}
 */
export function GetCrashReport() {
    return $Call.ByID(2071961624);
}

/**
 * @returns {$CancellablePromise<$models.DiagnosticsReview>}
 */
export function GetDiagnosticsReview() {
    return $Call.ByID(3103844513).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Display discovery is read-only and does not enable native input filtering.
 * @returns {$CancellablePromise<platform$0.DockLockDisplay[]>}
 */
export function GetDockMonitorLockDisplays() {
    return $Call.ByID(961307694).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<platform$0.DockMonitorLockState>}
 */
export function GetDockMonitorLockState() {
    return $Call.ByID(3014544674).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetDockState lets a newly loaded hidden webview catch up with a hover that
 * arrived before its event subscriptions were installed.
 * @returns {$CancellablePromise<$models.DockViewState | null>}
 */
export function GetDockState() {
    return $Call.ByID(1033939333).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetLauncherAppChoices is an explicit settings inventory. It performs no
 * window query, permission prompt or app activation and exposes no process IDs.
 * @returns {$CancellablePromise<$models.LauncherAppChoice[]>}
 */
export function GetLauncherAppChoices() {
    return $Call.ByID(1561877478).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {number} session
 * @returns {$CancellablePromise<launcher$0.Presentation>}
 */
export function GetLauncherState(session) {
    return $Call.ByID(1942731528, session).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.LauncherStatus>}
 */
export function GetLauncherStatus() {
    return $Call.ByID(3297738801).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {number} session
 * @returns {$CancellablePromise<$models.LauncherWidgetState>}
 */
export function GetLauncherWidgets(session) {
    return $Call.ByID(1662395444, session).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: platform$0.MediaPermission }>}
 */
export function GetMediaPermissions() {
    return $Call.ByID(3673411287).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {number} session
 * @returns {$CancellablePromise<$models.MediaViewState | null>}
 */
export function GetMediaState(session) {
    return $Call.ByID(3763583330, session).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetPermissions returns the grant state of the OS permissions the switcher
 * needs as JSON: {"accessibility":"granted|denied|unknown","screenRecording":...}.
 * The preferences UI polls this so a grant made in System Settings reflects live.
 * @returns {$CancellablePromise<string>}
 */
export function GetPermissions() {
    return $Call.ByID(2898822425);
}

/**
 * GetSettings returns the current settings as JSON for the preferences UI.
 * @returns {$CancellablePromise<string>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378);
}

/**
 * GetVersion returns the app version for the About tab.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * @param {widgets$0.Lease} lease
 * @param {string} actionToken
 * @returns {$CancellablePromise<widgets$0.ActionOptions>}
 */
export function GetWidgetActionOptions(lease, actionToken) {
    return $Call.ByID(1913639053, lease, actionToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {widgets$0.Lease} lease
 * @param {string} assetToken
 * @returns {$CancellablePromise<string>}
 */
export function GetWidgetAsset(lease, assetToken) {
    return $Call.ByID(1591270545, lease, assetToken);
}

/**
 * @returns {$CancellablePromise<$models.WidgetCatalogItem[]>}
 */
export function GetWidgetCatalog() {
    return $Call.ByID(1508342138).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.WidgetPackageStatus>}
 */
export function GetWidgetPackageStatus() {
    return $Call.ByID(2166434855).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * Hide pushes the hide event and hides the overlay window.
 * @returns {$CancellablePromise<void>}
 */
export function Hide() {
    return $Call.ByID(3538035797);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideSelectedApp() {
    return $Call.ByID(3942268823);
}

/**
 * HideSession retires only the presentation that requested dismissal. An old
 * controller callback must not hide an overlay that has since reopened.
 * @param {number} session
 * @returns {$CancellablePromise<void>}
 */
export function HideSession(session) {
    return $Call.ByID(3201711143, session);
}

/**
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function ImportMediaLyrics(session, revision) {
    return $Call.ByID(4054143088, session, revision);
}

/**
 * @param {string} token
 * @returns {$CancellablePromise<$models.WidgetCatalogItem>}
 */
export function InstallReviewedWidget(token) {
    return $Call.ByID(4223715965, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * InstallUpdate downloads and installs the release the update banner shows,
 * then relaunches the app. Progress rides the "update:progress" event.
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate() {
    return $Call.ByID(2443992793);
}

/**
 * IsPaused reports whether activation is currently suspended.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPaused() {
    return $Call.ByID(2583346675);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MinimizeSelected() {
    return $Call.ByID(1240045732);
}

/**
 * @param {number} session
 * @param {number} revision
 * @param {string} itemID
 * @returns {$CancellablePromise<void>}
 */
export function OpenDockFolderEntry(session, revision, itemID) {
    return $Call.ByID(1164782910, session, revision, itemID);
}

/**
 * OpenPermissionSettings opens the System Settings privacy pane for a permission,
 * guiding the user when a prior denial means the prompt no longer appears.
 * @param {string} kind
 * @returns {$CancellablePromise<void>}
 */
export function OpenPermissionSettings(kind) {
    return $Call.ByID(2426762731, kind);
}

/**
 * OpenPreferences shows and focuses the preferences window (created hidden at
 * startup; recreated defensively if macOS destroyed it). Invoked by the menubar
 * "Settings…" item and on first launch (onboarding).
 * @returns {$CancellablePromise<void>}
 */
export function OpenPreferences() {
    return $Call.ByID(3944193009);
}

/**
 * OpenURL opens a link in the user's default browser (About-tab links).
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(3584934946, url);
}

/**
 * PerformAction acts on the supplied identity without changing the selection.
 * @param {string} kind
 * @param {number} windowID
 * @param {number} appID
 * @returns {$CancellablePromise<actions$0.Result>}
 */
export function PerformAction(kind, windowID, appID) {
    return $Call.ByID(280563800, kind, windowID, appID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} session
 * @param {number} revision
 * @param {string} kind
 * @param {domain$0.WindowID} windowID
 * @param {boolean} fullscreen
 * @returns {$CancellablePromise<void>}
 */
export function PerformAutomationPreviewAction(session, revision, kind, windowID, fullscreen) {
    return $Call.ByID(513435453, session, revision, kind, windowID, fullscreen);
}

/**
 * @param {number} session
 * @param {string} kind
 * @param {number} windowID
 * @param {number} appID
 * @returns {$CancellablePromise<actions$0.Result>}
 */
export function PerformDockAction(session, kind, windowID, appID) {
    return $Call.ByID(1943493959, session, kind, windowID, appID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Initial RPC admission uses the rendered revision. Once accepted, native
 * preparation keeps exact panel and track authority while progress/artwork can
 * update the view independently. Controller also checks its current owner epoch.
 * @param {number} session
 * @param {number} revision
 * @param {string} kind
 * @param {number} positionMS
 * @returns {$CancellablePromise<void>}
 */
export function PerformMediaAction(session, revision, kind, positionMS) {
    return $Call.ByID(2082824200, session, revision, kind, positionMS);
}

/**
 * @param {widgets$0.Lease} lease
 * @param {string} actionToken
 * @param {string} optionToken
 * @param {number | null} value
 * @returns {$CancellablePromise<void>}
 */
export function PerformWidgetAction(lease, actionToken, optionToken, value) {
    return $Call.ByID(4243588732, lease, actionToken, optionToken, value);
}

/**
 * The Wails factory creates only a scheduler here. Its native webview and panel
 * are constructed later on the UI queue, outside App.viewMu.
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<number>}
 */
export function PinMediaPanel(session, revision) {
    return $Call.ByID(900489102, session, revision);
}

/**
 * This explicit UI action may briefly move the pointer. Native code owns the
 * bounded attempt and must relinquish cursor restoration on physical takeover.
 * @param {number} session
 * @param {number} revision
 * @param {number} generation
 * @returns {$CancellablePromise<platform$0.DockPlacementResult>}
 */
export function PlaceDockOnSelectedMonitor(session, revision, generation) {
    return $Call.ByID(1589667255, session, revision, generation).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitSelectedApp() {
    return $Call.ByID(3876391122);
}

/**
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function ReloadMediaLyrics(session, revision) {
    return $Call.ByID(3208690520, session, revision);
}

/**
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMediaLyrics(session, revision) {
    return $Call.ByID(2634844375, session, revision);
}

/**
 * @param {string} digest
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWidgetPackage(digest) {
    return $Call.ByID(2737711739, digest);
}

/**
 * ReportCrash opens a prefilled GitHub issue containing the pending crash log
 * (truncated). Navigation sends that text to GitHub before issue submission.
 * @returns {$CancellablePromise<void>}
 */
export function ReportCrash() {
    return $Call.ByID(3313417902);
}

/**
 * RequestAccessibility triggers the OS Accessibility permission prompt (needed
 * for the global hotkey and window actions).
 * @returns {$CancellablePromise<void>}
 */
export function RequestAccessibility() {
    return $Call.ByID(3385258050);
}

/**
 * @param {number} session
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function RequestDockFolderAccess(session, revision) {
    return $Call.ByID(1355609963, session, revision);
}

/**
 * RequestScreenRecording triggers the OS Screen Recording permission prompt
 * (needed for live window thumbnails).
 * @returns {$CancellablePromise<void>}
 */
export function RequestScreenRecording() {
    return $Call.ByID(3953002405);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Reverse() {
    return $Call.ByID(2687580445);
}

/**
 * @returns {$CancellablePromise<$models.WidgetPackageReview>}
 */
export function ReviewLocalWidgetPackage() {
    return $Call.ByID(460648480).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @param {string} token
 * @returns {$CancellablePromise<platform$0.DiagnosticExportResult>}
 */
export function SaveDiagnosticsReport(token) {
    return $Call.ByID(1276106854, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * SaveSettings serializes saves and publishes only successfully persisted settings.
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(jsonStr) {
    return $Call.ByID(1949631069, jsonStr);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function Select(index) {
    return $Call.ByID(149583269, index);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function SelectApp(id) {
    return $Call.ByID(523317996, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function SelectAppWindow(id) {
    return $Call.ByID(76282064, id);
}

/**
 * @param {number} session
 * @param {number} revision
 * @param {domain$0.WindowID} id
 * @returns {$CancellablePromise<void>}
 */
export function SelectAutomationPreview(session, revision, id) {
    return $Call.ByID(2322291942, session, revision, id);
}

/**
 * @param {number} session
 * @param {number} revision
 * @param {string} kind
 * @returns {$CancellablePromise<void>}
 */
export function SelectDockContent(session, revision, kind) {
    return $Call.ByID(2963493651, session, revision, kind);
}

/**
 * @param {number} session
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function SelectDockWindow(session, id) {
    return $Call.ByID(1507952022, session, id);
}

/**
 * @param {number} epoch
 * @param {string} displayUUID
 * @param {number} session
 * @param {string} profileID
 * @param {string} stackID
 * @param {string} instanceID
 * @returns {$CancellablePromise<void>}
 */
export function SelectLauncherWidget(epoch, displayUUID, session, profileID, stackID, instanceID) {
    return $Call.ByID(3729375001, epoch, displayUUID, session, profileID, stackID, instanceID);
}

/**
 * @param {number} session
 * @param {number} revision
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SetAutomationPreviewSize(session, revision, width, height) {
    return $Call.ByID(3307079785, session, revision, width, height);
}

/**
 * @param {number} session
 * @param {number} revision
 * @param {string} field
 * @param {string} direction
 * @param {boolean} foldersFirst
 * @returns {$CancellablePromise<void>}
 */
export function SetDockFolderSort(session, revision, field, direction, foldersFirst) {
    return $Call.ByID(3148788948, session, revision, field, direction, foldersFirst);
}

/**
 * @param {number} session
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SetDockPanelSize(session, width, height) {
    return $Call.ByID(1080314307, session, width, height);
}

/**
 * SetDockPreviewRegions publishes clipped panel-local card geometry. Native
 * code copies this policy and captures one immutable target at gesture begin.
 * @param {number} session
 * @param {number} revision
 * @param {$models.DockPreviewRegion[]} regions
 * @returns {$CancellablePromise<void>}
 */
export function SetDockPreviewRegions(session, revision, regions) {
    return $Call.ByID(3579515437, session, revision, regions);
}

/**
 * @param {number} session
 * @param {number} revision
 * @param {number} offsetMS
 * @returns {$CancellablePromise<void>}
 */
export function SetMediaLyricsOffset(session, revision, offsetMS) {
    return $Call.ByID(3423128546, session, revision, offsetMS);
}

/**
 * @param {number} session
 * @param {number} revision
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SetMediaPanelSize(session, revision, width, height) {
    return $Call.ByID(143498724, session, revision, width, height);
}

/**
 * SetPaused suspends or resumes activation, persists the choice, and reflects it
 * in the menubar. While paused the global hotkey does not open the switcher.
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetPaused(paused) {
    return $Call.ByID(786888629, paused);
}

/**
 * @param {string} q
 * @returns {$CancellablePromise<void>}
 */
export function SetSearch(q) {
    return $Call.ByID(1454005219, q);
}

/**
 * Show reveals the overlay window and pushes the initial state. If the
 * preferences window is open it is dismissed first. The overlay is shown
 * WITHOUT activating the app (v3 Show is a bare makeKeyAndOrderFront): the
 * previously active app keeps focus, so the active-app scope filter keeps
 * seeing the real frontmost app — activating here was the v2 switching bug.
 * @param {switcher$0.State} st
 * @returns {$CancellablePromise<void>}
 */
export function Show(st) {
    return $Call.ByID(2781088484, st);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartDiagnosticsRecording() {
    return $Call.ByID(2282172420);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopDiagnosticsRecording() {
    return $Call.ByID(76990490);
}

/**
 * TogglePause serializes read-modify-write with other settings changes.
 * @returns {$CancellablePromise<boolean>}
 */
export function TogglePause() {
    return $Call.ByID(564640869);
}

/**
 * Update pushes a new state to the visible overlay.
 * @param {switcher$0.State} st
 * @returns {$CancellablePromise<void>}
 */
export function Update(st) {
    return $Call.ByID(4141298428, st);
}

/**
 * Recovery changes runtime admission before persistence. A failed save leaves
 * the launcher disabled until recovery succeeds and the user enables it again.
 * @returns {$CancellablePromise<void>}
 */
export function UseNativeDock() {
    return $Call.ByID(421143656);
}

// Private type creation functions
const $$createType0 = platform$0.MediaPermission.createFrom;
const $$createType1 = actions$0.Result.createFrom;
const $$createType2 = $models.AutomationPreviewViewState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.DiagnosticsReview.createFrom;
const $$createType5 = platform$0.DockLockDisplay.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = platform$0.DockMonitorLockState.createFrom;
const $$createType8 = $models.DockViewState.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.LauncherAppChoice.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = launcher$0.Presentation.createFrom;
const $$createType13 = $models.LauncherStatus.createFrom;
const $$createType14 = $models.LauncherWidgetState.createFrom;
const $$createType15 = $Create.Map($Create.Any, $$createType0);
const $$createType16 = $models.MediaViewState.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = widgets$0.ActionOptions.createFrom;
const $$createType19 = $models.WidgetCatalogItem.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.WidgetPackageStatus.createFrom;
const $$createType22 = platform$0.DockPlacementResult.createFrom;
const $$createType23 = $models.WidgetPackageReview.createFrom;
const $$createType24 = platform$0.DiagnosticExportResult.createFrom;
