// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails-bound service. It owns the platform backend and the switcher
 * controller, implements switcher.View by emitting Wails events, and exposes
 * the controller's actions plus settings access to the frontend. It holds no
 * business logic of its own.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as switcher$0 from "./internal/switcher/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Advance() {
    return $Call.ByID(3974603045);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(2191755235);
}

/**
 * CancelShortcutCapture disarms a pending shortcut capture (the recorder
 * input lost focus).
 * @returns {$CancellablePromise<void>}
 */
export function CancelShortcutCapture() {
    return $Call.ByID(1824023725);
}

/**
 * CaptureShortcut arms native chord recording for the preferences UI and
 * blocks until the next chord pressed anywhere — including Command+Tab and
 * the switcher's own chord, which never reach the webview. Returns "" when
 * cancelled (Escape), timed out, or unsupported (stub platforms).
 * @returns {$CancellablePromise<string>}
 */
export function CaptureShortcut() {
    return $Call.ByID(1771599287);
}

/**
 * CheckForUpdates runs a release check now and opens the About tab, where the
 * update banner (with the install button) appears when a newer version
 * exists. The manual check never auto-installs, even under the "auto" policy.
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2675659504);
}

/**
 * ClosePreferences hides the preferences window and returns the app to the
 * accessory policy (no Dock icon).
 * @returns {$CancellablePromise<void>}
 */
export function ClosePreferences() {
    return $Call.ByID(3493222023);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseSelected() {
    return $Call.ByID(2868361114);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Confirm() {
    return $Call.ByID(3228319335);
}

/**
 * DismissCrashReport discards the pending crash log.
 * @returns {$CancellablePromise<void>}
 */
export function DismissCrashReport() {
    return $Call.ByID(2108673700);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function FullscreenSelected() {
    return $Call.ByID(529416953);
}

/**
 * GetCrashReport returns the previous run's crash log, or "" when there is
 * none (or the policy is "never").
 * @returns {$CancellablePromise<string>}
 */
export function GetCrashReport() {
    return $Call.ByID(2071961624);
}

/**
 * GetPermissions returns the grant state of the OS permissions the switcher
 * needs as JSON: {"accessibility":"granted|denied|unknown","screenRecording":...}.
 * The preferences UI polls this so a grant made in System Settings reflects live.
 * @returns {$CancellablePromise<string>}
 */
export function GetPermissions() {
    return $Call.ByID(2898822425);
}

/**
 * GetSettings returns the current settings as JSON for the preferences UI.
 * @returns {$CancellablePromise<string>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378);
}

/**
 * GetVersion returns the app version for the About tab.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * Hide pushes the hide event and hides the overlay window.
 * @returns {$CancellablePromise<void>}
 */
export function Hide() {
    return $Call.ByID(3538035797);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideSelectedApp() {
    return $Call.ByID(3942268823);
}

/**
 * InstallUpdate downloads and installs the release the update banner shows,
 * then relaunches the app. Progress rides the "update:progress" event.
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate() {
    return $Call.ByID(2443992793);
}

/**
 * IsPaused reports whether activation is currently suspended.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPaused() {
    return $Call.ByID(2583346675);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MinimizeSelected() {
    return $Call.ByID(1240045732);
}

/**
 * OpenPermissionSettings opens the System Settings privacy pane for a permission,
 * guiding the user when a prior denial means the prompt no longer appears.
 * @param {string} kind
 * @returns {$CancellablePromise<void>}
 */
export function OpenPermissionSettings(kind) {
    return $Call.ByID(2426762731, kind);
}

/**
 * OpenPreferences shows and focuses the preferences window (created hidden at
 * startup; recreated defensively if macOS destroyed it). Invoked by the menubar
 * "Settings…" item and on first launch (onboarding).
 * @returns {$CancellablePromise<void>}
 */
export function OpenPreferences() {
    return $Call.ByID(3944193009);
}

/**
 * OpenURL opens a link in the user's default browser (About-tab links).
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(3584934946, url);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitSelectedApp() {
    return $Call.ByID(3876391122);
}

/**
 * ReportCrash opens a prefilled GitHub issue containing the pending crash log
 * (truncated), so the user sees exactly what is shared before submitting.
 * @returns {$CancellablePromise<void>}
 */
export function ReportCrash() {
    return $Call.ByID(3313417902);
}

/**
 * RequestAccessibility triggers the OS Accessibility permission prompt (needed
 * for the global hotkey and window actions).
 * @returns {$CancellablePromise<void>}
 */
export function RequestAccessibility() {
    return $Call.ByID(3385258050);
}

/**
 * RequestScreenRecording triggers the OS Screen Recording permission prompt
 * (needed for live window thumbnails).
 * @returns {$CancellablePromise<void>}
 */
export function RequestScreenRecording() {
    return $Call.ByID(3953002405);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Reverse() {
    return $Call.ByID(2687580445);
}

/**
 * SaveSettings validates, applies, and persists settings from the preferences
 * UI, then re-registers hotkeys to reflect any chord changes.
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(jsonStr) {
    return $Call.ByID(1949631069, jsonStr);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function Select(index) {
    return $Call.ByID(149583269, index);
}

/**
 * SetPaused suspends or resumes activation, persists the choice, and reflects it
 * in the menubar. While paused the global hotkey does not open the switcher.
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetPaused(paused) {
    return $Call.ByID(786888629, paused);
}

/**
 * @param {string} q
 * @returns {$CancellablePromise<void>}
 */
export function SetSearch(q) {
    return $Call.ByID(1454005219, q);
}

/**
 * Show reveals the overlay window and pushes the initial state. If the
 * preferences window is open it is dismissed first. The overlay is shown
 * WITHOUT activating the app (v3 Show is a bare makeKeyAndOrderFront): the
 * previously active app keeps focus, so the active-app scope filter keeps
 * seeing the real frontmost app — activating here was the v2 switching bug.
 * @param {switcher$0.State} st
 * @returns {$CancellablePromise<void>}
 */
export function Show(st) {
    return $Call.ByID(2781088484, st);
}

/**
 * TogglePause flips the paused state and returns the new value.
 * @returns {$CancellablePromise<boolean>}
 */
export function TogglePause() {
    return $Call.ByID(564640869);
}

/**
 * Update pushes a new state to the visible overlay.
 * @param {switcher$0.State} st
 * @returns {$CancellablePromise<void>}
 */
export function Update(st) {
    return $Call.ByID(4141298428, st);
}
