// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dock$0 from "./internal/dock/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as media$0 from "./internal/media/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "./internal/platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as switcher$0 from "./internal/switcher/models.js";

/**
 * Automation previews have their own owner and never impersonate a Dock item.
 */
export class AutomationPreviewViewState {
    /**
     * Creates a new AutomationPreviewViewState instance.
     * @param {Partial<AutomationPreviewViewState>} [$$source = {}] - The source object to create the AutomationPreviewViewState.
     */
    constructor($$source = {}) {
        if (!("open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["open"] = false;
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session"] = 0;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {switcher$0.Entry[]}
             */
            this["entries"] = [];
        }
        if (!("selectedWindowId" in $$source)) {
            /**
             * @member
             * @type {domain$0.WindowID}
             */
            this["selectedWindowId"] = 0;
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {config$0.Appearance}
             */
            this["appearance"] = (new config$0.Appearance());
        }
        if (!("cardSpacingPx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cardSpacingPx"] = 0;
        }
        if (!("emptyReason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["emptyReason"] = "";
        }
        if (!("frames" in $$source)) {
            /**
             * @member
             * @type {{ [_ in domain$0.WindowID]?: string }}
             */
            this["frames"] = {};
        }
        if (!("frameSequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["frameSequence"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutomationPreviewViewState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutomationPreviewViewState}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField4_0($$parsedSource["entries"]);
        }
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField6_0($$parsedSource["appearance"]);
        }
        if ("frames" in $$parsedSource) {
            $$parsedSource["frames"] = $$createField9_0($$parsedSource["frames"]);
        }
        return new AutomationPreviewViewState(/** @type {Partial<AutomationPreviewViewState>} */($$parsedSource));
    }
}

export class DockBounds {
    /**
     * Creates a new DockBounds instance.
     * @param {Partial<DockBounds>} [$$source = {}] - The source object to create the DockBounds.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["h"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockBounds instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockBounds}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockBounds(/** @type {Partial<DockBounds>} */($$parsedSource));
    }
}

export class DockItemView {
    /**
     * Creates a new DockItemView instance.
     * @param {Partial<DockItemView>} [$$source = {}] - The source object to create the DockItemView.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("appId" in $$source)) {
            /**
             * @member
             * @type {domain$0.AppID}
             */
            this["appId"] = 0;
        }
        if (!("bundleId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bundleId"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("bounds" in $$source)) {
            /**
             * @member
             * @type {DockBounds}
             */
            this["bounds"] = (new DockBounds());
        }
        if (!("screenId" in $$source)) {
            /**
             * @member
             * @type {domain$0.ScreenID}
             */
            this["screenId"] = 0;
        }
        if (!("edge" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["edge"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockItemView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockItemView}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField5_0($$parsedSource["bounds"]);
        }
        return new DockItemView(/** @type {Partial<DockItemView>} */($$parsedSource));
    }
}

export class DockPointer {
    /**
     * Creates a new DockPointer instance.
     * @param {Partial<DockPointer>} [$$source = {}] - The source object to create the DockPointer.
     */
    constructor($$source = {}) {
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session"] = 0;
        }
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("inside" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["inside"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockPointer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockPointer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockPointer(/** @type {Partial<DockPointer>} */($$parsedSource));
    }
}

export class DockPreviewRegion {
    /**
     * Creates a new DockPreviewRegion instance.
     * @param {Partial<DockPreviewRegion>} [$$source = {}] - The source object to create the DockPreviewRegion.
     */
    constructor($$source = {}) {
        if (!("windowId" in $$source)) {
            /**
             * @member
             * @type {domain$0.WindowID}
             */
            this["windowId"] = 0;
        }
        if (!("appId" in $$source)) {
            /**
             * @member
             * @type {domain$0.AppID}
             */
            this["appId"] = 0;
        }
        if (!("bounds" in $$source)) {
            /**
             * @member
             * @type {DockBounds}
             */
            this["bounds"] = (new DockBounds());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockPreviewRegion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockPreviewRegion}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField2_0($$parsedSource["bounds"]);
        }
        return new DockPreviewRegion(/** @type {Partial<DockPreviewRegion>} */($$parsedSource));
    }
}

export class DockViewState {
    /**
     * Creates a new DockViewState instance.
     * @param {Partial<DockViewState>} [$$source = {}] - The source object to create the DockViewState.
     */
    constructor($$source = {}) {
        if (!("contentKind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentKind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {dock$0.FolderState | null | undefined}
             */
            this["folder"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MediaViewState | null | undefined}
             */
            this["media"] = undefined;
        }
        if (!("open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["open"] = false;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session"] = 0;
        }
        if (!("item" in $$source)) {
            /**
             * @member
             * @type {DockItemView}
             */
            this["item"] = (new DockItemView());
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {switcher$0.Entry[]}
             */
            this["entries"] = [];
        }
        if (!("selectedWindowId" in $$source)) {
            /**
             * @member
             * @type {domain$0.WindowID}
             */
            this["selectedWindowId"] = 0;
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {config$0.Appearance}
             */
            this["appearance"] = (new config$0.Appearance());
        }
        if (!("cardSpacingPx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cardSpacingPx"] = 0;
        }
        if (!("emptyReason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["emptyReason"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DockPointer | null | undefined}
             */
            this["pointer"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("previewDragEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["previewDragEnabled"] = false;
        }
        if (!("dragGestureFloor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dragGestureFloor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockViewState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockViewState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        const $$createField6_0 = $$createType9;
        const $$createField7_0 = $$createType1;
        const $$createField9_0 = $$createType2;
        const $$createField12_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folder" in $$parsedSource) {
            $$parsedSource["folder"] = $$createField1_0($$parsedSource["folder"]);
        }
        if ("media" in $$parsedSource) {
            $$parsedSource["media"] = $$createField2_0($$parsedSource["media"]);
        }
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField6_0($$parsedSource["item"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField7_0($$parsedSource["entries"]);
        }
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField9_0($$parsedSource["appearance"]);
        }
        if ("pointer" in $$parsedSource) {
            $$parsedSource["pointer"] = $$createField12_0($$parsedSource["pointer"]);
        }
        return new DockViewState(/** @type {Partial<DockViewState>} */($$parsedSource));
    }
}

export class MediaArtworkView {
    /**
     * Creates a new MediaArtworkView instance.
     * @param {Partial<MediaArtworkView>} [$$source = {}] - The source object to create the MediaArtworkView.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["image"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaArtworkView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MediaArtworkView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaArtworkView(/** @type {Partial<MediaArtworkView>} */($$parsedSource));
    }
}

export class MediaLyricsView {
    /**
     * Creates a new MediaLyricsView instance.
     * @param {Partial<MediaLyricsView>} [$$source = {}] - The source object to create the MediaLyricsView.
     */
    constructor($$source = {}) {
        if (!("documentID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["documentID"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("cues" in $$source)) {
            /**
             * @member
             * @type {media$0.Cue[]}
             */
            this["cues"] = [];
        }
        if (!("offsetMS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offsetMS"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaLyricsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MediaLyricsView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cues" in $$parsedSource) {
            $$parsedSource["cues"] = $$createField3_0($$parsedSource["cues"]);
        }
        return new MediaLyricsView(/** @type {Partial<MediaLyricsView>} */($$parsedSource));
    }
}

export class MediaViewState {
    /**
     * Creates a new MediaViewState instance.
     * @param {Partial<MediaViewState>} [$$source = {}] - The source object to create the MediaViewState.
     */
    constructor($$source = {}) {
        if (!("interactionEpoch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interactionEpoch"] = 0;
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session"] = 0;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["open"] = false;
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("pinnable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinnable"] = false;
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {platform$0.MediaProvider}
             */
            this["provider"] = platform$0.MediaProvider.$zero;
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {platform$0.MediaScope}
             */
            this["scope"] = (new platform$0.MediaScope());
        }
        if (!("sample" in $$source)) {
            /**
             * @member
             * @type {platform$0.MediaSample}
             */
            this["sample"] = (new platform$0.MediaSample());
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {config$0.Appearance}
             */
            this["appearance"] = (new config$0.Appearance());
        }
        if (!("artwork" in $$source)) {
            /**
             * @member
             * @type {MediaArtworkView}
             */
            this["artwork"] = (new MediaArtworkView());
        }
        if (!("lyrics" in $$source)) {
            /**
             * @member
             * @type {MediaLyricsView}
             */
            this["lyrics"] = (new MediaLyricsView());
        }
        if (!("positionMS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["positionMS"] = 0;
        }
        if (!("activeCue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeCue"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaViewState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MediaViewState}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType14;
        const $$createField8_0 = $$createType15;
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType16;
        const $$createField11_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField7_0($$parsedSource["scope"]);
        }
        if ("sample" in $$parsedSource) {
            $$parsedSource["sample"] = $$createField8_0($$parsedSource["sample"]);
        }
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField9_0($$parsedSource["appearance"]);
        }
        if ("artwork" in $$parsedSource) {
            $$parsedSource["artwork"] = $$createField10_0($$parsedSource["artwork"]);
        }
        if ("lyrics" in $$parsedSource) {
            $$parsedSource["lyrics"] = $$createField11_0($$parsedSource["lyrics"]);
        }
        return new MediaViewState(/** @type {Partial<MediaViewState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = switcher$0.Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = config$0.Appearance.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = DockBounds.createFrom;
const $$createType5 = dock$0.FolderState.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = MediaViewState.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = DockItemView.createFrom;
const $$createType10 = DockPointer.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = media$0.Cue.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = platform$0.MediaScope.createFrom;
const $$createType15 = platform$0.MediaSample.createFrom;
const $$createType16 = MediaArtworkView.createFrom;
const $$createType17 = MediaLyricsView.createFrom;
