// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dock$0 from "./internal/dock/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as switcher$0 from "./internal/switcher/models.js";

export class DockBounds {
    /**
     * Creates a new DockBounds instance.
     * @param {Partial<DockBounds>} [$$source = {}] - The source object to create the DockBounds.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["h"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockBounds instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockBounds}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockBounds(/** @type {Partial<DockBounds>} */($$parsedSource));
    }
}

export class DockItemView {
    /**
     * Creates a new DockItemView instance.
     * @param {Partial<DockItemView>} [$$source = {}] - The source object to create the DockItemView.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("appId" in $$source)) {
            /**
             * @member
             * @type {domain$0.AppID}
             */
            this["appId"] = 0;
        }
        if (!("bundleId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bundleId"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("bounds" in $$source)) {
            /**
             * @member
             * @type {DockBounds}
             */
            this["bounds"] = (new DockBounds());
        }
        if (!("screenId" in $$source)) {
            /**
             * @member
             * @type {domain$0.ScreenID}
             */
            this["screenId"] = 0;
        }
        if (!("edge" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["edge"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockItemView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockItemView}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField5_0($$parsedSource["bounds"]);
        }
        return new DockItemView(/** @type {Partial<DockItemView>} */($$parsedSource));
    }
}

export class DockPointer {
    /**
     * Creates a new DockPointer instance.
     * @param {Partial<DockPointer>} [$$source = {}] - The source object to create the DockPointer.
     */
    constructor($$source = {}) {
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session"] = 0;
        }
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("inside" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["inside"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockPointer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockPointer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockPointer(/** @type {Partial<DockPointer>} */($$parsedSource));
    }
}

export class DockPreviewRegion {
    /**
     * Creates a new DockPreviewRegion instance.
     * @param {Partial<DockPreviewRegion>} [$$source = {}] - The source object to create the DockPreviewRegion.
     */
    constructor($$source = {}) {
        if (!("windowId" in $$source)) {
            /**
             * @member
             * @type {domain$0.WindowID}
             */
            this["windowId"] = 0;
        }
        if (!("appId" in $$source)) {
            /**
             * @member
             * @type {domain$0.AppID}
             */
            this["appId"] = 0;
        }
        if (!("bounds" in $$source)) {
            /**
             * @member
             * @type {DockBounds}
             */
            this["bounds"] = (new DockBounds());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockPreviewRegion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockPreviewRegion}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField2_0($$parsedSource["bounds"]);
        }
        return new DockPreviewRegion(/** @type {Partial<DockPreviewRegion>} */($$parsedSource));
    }
}

export class DockViewState {
    /**
     * Creates a new DockViewState instance.
     * @param {Partial<DockViewState>} [$$source = {}] - The source object to create the DockViewState.
     */
    constructor($$source = {}) {
        if (!("contentKind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentKind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {dock$0.FolderState | null | undefined}
             */
            this["folder"] = undefined;
        }
        if (!("open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["open"] = false;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session"] = 0;
        }
        if (!("item" in $$source)) {
            /**
             * @member
             * @type {DockItemView}
             */
            this["item"] = (new DockItemView());
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {switcher$0.Entry[]}
             */
            this["entries"] = [];
        }
        if (!("selectedWindowId" in $$source)) {
            /**
             * @member
             * @type {domain$0.WindowID}
             */
            this["selectedWindowId"] = 0;
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {config$0.Appearance}
             */
            this["appearance"] = (new config$0.Appearance());
        }
        if (!("cardSpacingPx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cardSpacingPx"] = 0;
        }
        if (!("emptyReason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["emptyReason"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DockPointer | null | undefined}
             */
            this["pointer"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("previewDragEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["previewDragEnabled"] = false;
        }
        if (!("dragGestureFloor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dragGestureFloor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockViewState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockViewState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField8_0 = $$createType6;
        const $$createField11_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folder" in $$parsedSource) {
            $$parsedSource["folder"] = $$createField1_0($$parsedSource["folder"]);
        }
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField5_0($$parsedSource["item"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField6_0($$parsedSource["entries"]);
        }
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField8_0($$parsedSource["appearance"]);
        }
        if ("pointer" in $$parsedSource) {
            $$parsedSource["pointer"] = $$createField11_0($$parsedSource["pointer"]);
        }
        return new DockViewState(/** @type {Partial<DockViewState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DockBounds.createFrom;
const $$createType1 = dock$0.FolderState.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = DockItemView.createFrom;
const $$createType4 = switcher$0.Entry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = config$0.Appearance.createFrom;
const $$createType7 = DockPointer.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
