// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * AppID uniquely identifies a running application. On macOS this maps to the
 * owning process id (pid).
 * @typedef {$models.AppID} AppID
 */

/**
 * ScreenID identifies a physical display. Zero means "unknown".
 * @typedef {$models.ScreenID} ScreenID
 */

/**
 * SpaceID identifies a macOS Space (virtual desktop). Zero means "unknown".
 * @typedef {$models.SpaceID} SpaceID
 */

/**
 * WindowID uniquely identifies a window for the lifetime of the process.
 * On macOS this maps to a CGWindowID.
 * @typedef {$models.WindowID} WindowID
 */
