// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppID uniquely identifies a running application. On macOS this maps to the
 * owning process id (pid).
 * @typedef {number} AppID
 */

/**
 * ScreenID identifies a physical display. Zero means "unknown".
 * @typedef {number} ScreenID
 */

/**
 * SpaceID identifies a macOS Space (virtual desktop). Zero means "unknown".
 * @typedef {number} SpaceID
 */

/**
 * WindowID uniquely identifies a window for the lifetime of the process.
 * On macOS this maps to a CGWindowID.
 * @typedef {number} WindowID
 */
